version: '3.8'

name: postgres

services:
  postgres:
    extends:
      file: ./docker-compose-postgres.yml
      service: postgres

  adminer:
    extends:
      file: ./docker-compose-postgres.yml
      service: adminer

volumes:
  postgres_data:
