version: '3.8'

name: postgres

services:
  postgres:
    extends:
      file: ./docker-compose-postgres.yml
      service: postgres
    ports:
      - 5432:5432

  adminer:
    extends:
      file: ./docker-compose-postgres.yml
      service: adminer

volumes:
  postgres_data:
